mutation CreateSettingPomodoroInput(
  $createSettingPomodoroInput: CreateSettingPomodoroInput!
) {
  createSettingPomodoro(
    createSettingPomodoroInput: $createSettingPomodoroInput
  ) {
    ...SettingPomodoroInfoFields
  }
}
